### PR TITLE
chore: update to angular13 + update all other deps

### LINKED ISSUE #66: Angular 13
```
[ ] Bug
[ ] Build issue
[x] Feature request
```

#### Version info 

```
Angular:
Angular CLI: 13.0.3
ngx-countup: ^7.3.3
```

#### Description

When compiling with Angular 13, it shows the following message. The library seems to work fine.

```
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-countup [es2015/esm2015] (git+https://github.com/inorganik/ngx-countUp.git)
Encourage the library authors to publish an Ivy distribution.

```

### PR DESCRIPTION
**Pull request by bboehm86**
Noteworthy:
* clean up unused deps
* move from tslint to eslint
* update to latest jest + migrate config
* update countup.js to 2.0.8

---

> **Info**
> You should remove the `"ngx-countup"` entry from the `transformIgnorePatterns` in the `jest.config.js` once the version in the root `package.json` is up-to-date.

closes #66

### CODE REVIEW

**Comment by inorganik** [comment]
this looks like a great PR! Thanks I'll take a look very soon.

**Review by inorganik — COMMENTED** [review]
I see you added jest - but there are no specs. In this case of this lib I don't think it's really necessary. Did you have some tests in mind?

**Comment by bboehm86** [comment]
> I see you added jest - but there are no specs. In this case of this lib I don't think it's really necessary. Did you have some tests in mind?

I just updated jest with the rest, it was already there and I didn’t want to leave it broken… but no I don’t think there ist much potential for tests here :)

**Comment by inorganik** [comment]
Merged, plus I updated the version and published on npm. 🎉

**Pull request merged**
